.PHONY: build proto
.DEFAULT_GOAL := help
BINARY_NAME=didctl
DOCKER_IMAGE=didctl
VERSION_TAG=0.5.1

# Linker tags
# https://golang.org/cmd/link/
LD_FLAGS += -s -w
LD_FLAGS += -X github.com/bryk-io/did-method/client/cli/cmd.coreVersion=$(VERSION_TAG)
LD_FLAGS += -X github.com/bryk-io/did-method/client/cli/cmd.buildTimestamp=$(shell date +'%s')
LD_FLAGS += -X github.com/bryk-io/did-method/client/cli/cmd.buildCode=$(shell git log --pretty=format:'%H' -n1)

## help: Prints this help message
help:
	@echo "Commands available"
	@sed -n 's/^##//p' ${MAKEFILE_LIST} | column -t -s ':' | sed -e 's/^/ /' | sort

## lint: Static analysis
lint:
	helm lint helm/*
	golangci-lint run -v ./...

## test: Run unit tests excluding the vendor dependencies
test:
	go test -race -cover -v -failfast ./...

## scan: Look for knonwn vulnerabilities in the project dependencies
# https://github.com/sonatype-nexus-community/nancy
scan:
	@nancy -quiet go.sum

## release: Prepare assets for a new tagged release
release:
	@-rm -rf release-$(VERSION_TAG)
	mkdir release-$(VERSION_TAG)
	make build-for os=linux arch=amd64 dest=release-$(VERSION_TAG)/
	make build-for os=darwin arch=amd64 dest=release-$(VERSION_TAG)/
	make build-for os=windows arch=amd64 suffix=".exe" dest=release-$(VERSION_TAG)/

## build: Build for the current architecture in use, intended for devevelopment
build:
	go build -v -ldflags '$(LD_FLAGS)' -o $(BINARY_NAME) github.com/bryk-io/did-method/client/cli

## build-for: Build the availabe binaries for the specified 'os' and 'arch'
build-for:
	CGO_ENABLED=0 GOOS=$(os) GOARCH=$(arch) \
	go build -v -ldflags '$(LD_FLAGS)' \
	-o $(dest)$(BINARY_NAME)_$(VERSION_TAG)_$(os)_$(arch)$(suffix) github.com/bryk-io/did-method/client/cli

## install: Install the binary to GOPATH and keep cached all compiled artifacts
install:
	@go build -v -ldflags $(LD_FLAGS) -i -o ${GOPATH}/bin/$(BINARY_NAME) github.com/bryk-io/did-method/client/cli

## clean: Verify dependencies and remove intermediary products
clean:
	go clean
	go mod tidy
	go mod verify
	go mod vendor

## updates: List available updates for direct dependencies
# https://github.com/golang/go/wiki/Modules#how-to-upgrade-and-downgrade-dependencies
updates:
	@go list -u -f '{{if (and (not (or .Main .Indirect)) .Update)}}{{.Path}}: {{.Version}} -> {{.Update.Version}}{{end}}' -m all 2> /dev/null

## proto: Compile protocol buffers and RPC services
proto:
	# Validate styles
	docker run --rm -t -v `pwd`:/workdir proto-builder:1.9.0 prototool lint proto/v1
	docker run --rm -t -v `pwd`:/workdir proto-builder:1.9.0 prototool format -w -f proto/v1

	# Process files
	docker run --rm -t -v `pwd`:/workdir proto-builder:1.9.0 prototool generate

	# Generate service descriptors
	docker run --rm -t -v `pwd`:/workdir proto-builder:1.9.0 prototool descriptor-set --include-imports --include-source-info -o proto/v1/descriptor.bin proto

	# Fix gRPC-Gateway generated code
	# https://github.com/grpc-ecosystem/grpc-gateway/issues/229
	sed -i '' "s/empty.Empty/types.Empty/g" proto/v1/*.pb.gw.go

	# Remove comment added by the gateway generator to avoid polluting
	# the package documentation
	@-sed -i '' '/\/\*/,/*\//d' proto/v1/*.pb.gw.go

	# Remove empty files generated by protoc-gen-go-json
	#for ff in proto/v1/*.pb.json.go; do \
    #   if [ `grep -c '' $$ff` -le 11 ];then \
    #      rm $$ff; \
    #   fi \
    #done

	# Fix inconsistent output from protoc-gen-govalidators
	#@-gofmt -w proto/v1/*.validator.pb.go

## ca-roots: Generate the list of valid CA certificates
ca-roots:
	@docker run -dit --rm --name ca-roots debian:stable-slim
	@docker exec --privileged ca-roots sh -c "apt update"
	@docker exec --privileged ca-roots sh -c "apt install -y ca-certificates"
	@docker exec --privileged ca-roots sh -c "cat /etc/ssl/certs/* > /ca-roots.crt"
	@docker cp ca-roots:/ca-roots.crt ca-roots.crt
	@docker stop ca-roots

## docker: Build docker image
docker:
	@make build-for os=linux arch=amd64
	@-docker rmi $(DOCKER_IMAGE):$(VERSION_TAG)
	@docker build --build-arg VERSION_TAG="$(VERSION_TAG)" --rm -t $(DOCKER_IMAGE):$(VERSION_TAG) .
	@-rm $(BINARY_NAME)_$(VERSION_TAG)_linux_amd64

## ci-update: Update the signature on the CI configuration file
ci-update:
	drone sign bryk-io/did-method --save
