client:
  node: did.bryk.io:443
  tls: true
  timeout: 5
resolver:
  - method: algo
    endpoint: https://did-agent.aidtech.network/v1/retrieve/{{.Method}}/{{.Subject}}
    protocol: http
  - method: bryk
    endpoint: https://did.bryk.io/v1/retrieve/{{.Method}}/{{.Subject}}
    protocol: http
  - method: ccp
    endpoint: https://did.baidu.com/v1/did/resolve/{{.DID}}
    protocol: http
  - method: stack
    endpoint: https://core.blockstack.org/v1/dids/{{.DID}}
    protocol: http
