apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cc.fullname" . }}
  labels:
  {{- include "cc.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- toYaml .Values.configuration | nindent 4 }}
