apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cc.fullname" . }}
  labels:
    {{- include "cc.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "cc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
            {{- include "cc.selectorLabels" . | nindent 8 }}
    spec:
    {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
        {{- end }}
    {{- end }}
      serviceAccountName: {{ include "cc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "cc.fullname" . }}
        {{- if .Values.tlsSecretName }}
        - name: tls
          secret:
            secretName: {{ .Values.tlsSecretName }}
        {{- end }}
      containers:
        - name: main
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config
              mountPath: /etc/{{ .Chart.Name }}
            {{- if .Values.tlsSecretName }}
            - name: tls
              mountPath: /etc/{{ .Chart.Name }}/tls
              readOnly: true
            {{- end }}
          args:
            - "agent"
          ports:
            - name: rpc
              protocol: TCP
              containerPort: {{ .Values.access.port }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              {{- if .Values.configuration.agent.rpc.tls.enabled }}
              scheme: HTTPS
              {{- end }}
              path: /v1/ping
              port: rpc
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              {{- if .Values.configuration.agent.rpc.tls.enabled }}
              scheme: HTTPS
              {{- end }}
              path: /v1/ping
              port: rpc
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
