{{- if .Values.access.ingress.enabled -}}
{{- if .Values.access.ingress.tlsPassthrough -}}
{{- $fullName := include "cc.fullname" . -}}
{{- $svcPort := .Values.access.port -}}
{{- if and .Values.access.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.access.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.access.ingress.annotations "kubernetes.io/ingress.class" .Values.access.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "cc.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "https"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    {{- with .Values.access.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.access.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.access.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.access.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
{{- else -}}
{{- $fullName := include "cc.fullname" . -}}
{{- $svcPort := .Values.access.port -}}
{{- $httpBackendProtocol := ternary "https" "http" .Values.access.ingress.http.secureBackend -}}
{{- if and .Values.access.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.access.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.access.ingress.annotations "kubernetes.io/ingress.class" .Values.access.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "cc.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: {{ $httpBackendProtocol }}
    {{- if and .Values.tlsSecretName .Values.access.ingress.tls }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
    {{- with .Values.access.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.access.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.access.ingress.className }}
  {{- end }}
  {{- if and .Values.tlsSecretName .Values.access.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.access.ingress.host }}
      secretName: {{ .Values.tlsSecretName }}
  {{- end }}
  rules:
    - host: {{ .Values.access.ingress.host }}
      http:
        paths:
          {{- range .Values.access.ingress.http.paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
{{- end }}
---
{{ if and .Values.access.ingress.grpc.enabled (not (.Values.access.ingress.tlsPassthrough)) -}}
{{- $fullName := include "cc.fullname" . -}}
{{- $svcPort := .Values.access.port -}}
{{- $grpcBackendProtocol := ternary "grpcs" "grpc" .Values.access.ingress.grpc.secureBackend -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ printf "%s-%s" $fullName "grpc" }}
  labels:
    {{- include "cc.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: {{ $grpcBackendProtocol }}
    {{- with .Values.access.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.access.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.access.ingress.className }}
  {{- end }}
  {{- if and .Values.tlsSecretName .Values.access.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.access.ingress.host }}
      secretName: {{ .Values.tlsSecretName }}
  {{- end }}
  rules:
    - host: {{ .Values.access.ingress.host }}
      http:
        paths:
          {{- range .Values.access.ingress.grpc.services }}
          - path: /{{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
{{- end -}}
{{- end -}}
