apiVersion: v1
kind: Service
metadata:
  name: {{ include "cc.fullname" . }}
  labels:
    {{- include "cc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.access.serviceType }}
  ports:
    - port: {{ .Values.access.port }}
      targetPort: rpc
      protocol: TCP
      name: rpc
  selector:
    {{- include "cc.selectorLabels" . | nindent 4 }}
